#!/bin/bash
#
# By Sirupsen @ http://sirupsen.dk
# Original version: http://sirupsen.com/a-simple-imgur-bash-screenshot-utility
# Modifications by Florian Rathgeber @frathgeber (https://github.com/kynan)
#
# Description: Very simple script to make you
# select a region of your screen, which will be captured, and
# then uploaded. The URL will then be injected into your clipboard.
#
# Dependencies:
#
# Imgur Bash Upload Script (http://imgur.com/tools/imgurbash.sh)
# Comment: Must be in path (see below) with the name "imgur" (not imgur.sh)
#
# Scrot
# Comment: Scrot is what takes the actual screenshot.
#
# Xclip
# Comment: Xclip is what makes the script able to inject the direct url
# into your clipboard.
#
# libnotify*
# Comment: Will notify you whenever the direct URL is in the clipboard
#
# Installation:
#
# Move the file to a local bin. And put the path of this bin, into
# your path. (See: www.troubleshooters.com/linux/prepostpath.htm)
#
# From then on, you can either activate it via your terminal, or via
# your window manager or similar, so you can bind it to a keycombination. grep -E -o "<original_image>(.)*</original_image>" | 

rm snap-share.txt ; 
xsel -bc
echo -n | xclip -selection clipboard 
xsel -bc

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "http://i.imgur.com/[^<]*"
}

f=$(tempfile -d '/tmp' -s '.png')
scrot -d 4 -c $f
if [ -x `which imgur` ]; then
imgur $f >> snap-share.txt
rm snap-share.txt
imgur $f >> snap-share.txt
echo -n | xclip -selection clipboard 
xsel -bi < snap-share.txt
 xsel -bo
else
 echo "" >> snap-share.txt
 rm snap-share.txt
 uploadImage $f >> snap-share.txt
 echo -n | xclip -selection clipboard 
 xsel -bi < snap-share.txt
 xsel -bo
fi
rm -f $f
notify-send "Done. Press Ctrl+V to paste the URL of your shot! and click this notification to see the link. :)"
#xsel -bo|zenity --text-info --width 530
echo `xsel -bo`|xargs -0 notify-send

