#!/bin/bash

#setup
#-----
#new fake progressbar:

xsel -c -b
xsel -c
#xsel -c -b clears the clipboard
rm snap-share.txt ;
#double cleaning
echo -n | xclip -selection clipboard
xsel -bc

function uploadImage {
                        curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "http://i.imgur.com/[^<]*"
                      }

        #take the shot
        #------------
        f=$(tempfile -d '/tmp' -s '.png')
        scrot -d 7 $f

                  #new fake progressbar:
                  wmctrl -r "Get ready for the screenshot!" -b add,above &
                  (
                  echo "#...taking a screenshot in 4" ; sleep 1
                  echo "25"
                  echo "#...taking a screenshot in 3" ; sleep 1
                  echo "50"
                  echo "#...taking a screenshot in 2" ; sleep 1
                  echo "75"
                  echo "#...taking the shot in 1" ; sleep 1
                  echo "99"
                  echo "#          ...and     ...SAY CHEESE!!! :)" ; sleep 2
                  echo "100"
                  ) |
                  zenity --progress \
                    --text="Get ready!" \
                    --percentage=0 \
                    --auto-close \
                    --auto-kill --width=600 --height=200

                          if [ -x `which imgur` ]; then
                            sleep 2;
                            coproc { echo 0; sleep 1; echo 10; imgur $f >> snap-share.txt; echo 50;
                            rm snap-share.txt #double erase
                            imgur $f >> snap-share.txt; echo 60;
                            echo -n | xclip -selection clipboard
                            xsel -bi < snap-share.txt ; echo 80;
                            xsel -bo
                            echo 100; }
                            zenity --progress --text="Uploading your screenshot..." --auto-close <&${COPROC[0]} --width=600 --height=200 || kill $!
                                else
                                 echo "" >> snap-share.txt
                                 rm snap-share.txt
                                 uploadImage $f >> snap-share.txt
                                 echo -n | xclip -selection clipboard
                                 xsel -bi < snap-share.txt
                                 xsel -bo
                                 rm snap-share.txt
                        fi
rm -f $f

#notifications when the work is done.
  notify-send "Done. Press Ctrl+V to share your desktop screenshot. :)"
  #xsel -bo|zenity --text-info --width 530
  #echo `xsel -bo`|xargs -0 notify-send



#end.
