#!/bin/bash

#setup
#-----

xsel -c -b
xsel -c
#xsel -c -b clears the clipboard
rm snap-share.txt ;
#double cleaning
echo -n | xclip -selection clipboard
xsel -bc

function uploadImage {
                        curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "http://i.imgur.com/[^<]*"
                      }

        #take the shot
        #------------
        f=$(tempfile -d '/tmp' -s '.png')
        scrot -d 4 $f

                  #new fake progressbar:
                  sleep 1 && wmctrl -r "Get ready for the screenshot!" -b add,above &

                  (
                  echo "#...taking the shot in 4" ; sleep 1
                  echo "30"
                  echo "#...taking the shot in 4" ; sleep 1
                  echo "60"
                  echo "#...taking the shot in 2" ; sleep 1
                  echo "90"
              #    echo "#...taking the shot in 2" ; sleep 1
              #    echo "99"
                  echo "# NOW SAY CHEESE (or whisky!) :)" ; sleep 1
                  echo "100"
                  ) |
                  zenity --progress \
                    --title="Get ready for the screenshot!" \
                    --text="Get ready for the screenshot!" \
                    --percentage=0 \
                    --auto-close \
                    --auto-kill

                          if [ -x `which imgur` ]; then
                            coproc { echo 0; imgur $f >> snap-share.txt;
                            rm snap-share.txt #double erase
                            imgur $f >> snap-share.txt
                            echo -n | xclip -selection clipboard
                            xsel -bi < snap-share.txt
                            xsel -bo
                            echo 100; }
                            zenity --progress <&${COPROC[0]} || kill $!

                                else
                                 echo "" >> snap-share.txt
                                 rm snap-share.txt
                                 uploadImage $f >> snap-share.txt
                                 echo -n | xclip -selection clipboard
                                 xsel -bi < snap-share.txt
                                 xsel -bo
                                 rm snap-share.txt
                        fi
rm -f $f

#notifications when the work is done.
  notify-send "Done. Press Ctrl+V to share your desktop screenshot. :)"
  #xsel -bo|zenity --text-info --width 530
  echo `xsel -bo`|xargs -0 notify-send



#end.
