#!/bin/bash
#xsel -c -b clears the clipboard
xsel -c -b
xsel -c
rm snap-share.txt ;
#double cleaning
echo -n | xclip -selection clipboard
xsel -bc

function uploadImage {
  curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "http://i.imgur.com/[^<]*"
}

f=$(tempfile -d '/tmp' -s '.png')
scrot -d 4 -c $f
if [ -x `which imgur` ]; then
imgur $f >> snap-share.txt
rm snap-share.txt
imgur $f >> snap-share.txt
echo -n | xclip -selection clipboard
xsel -bi < snap-share.txt
 xsel -bo
else
 echo "" >> snap-share.txt
 rm snap-share.txt
 uploadImage $f >> snap-share.txt
 echo -n | xclip -selection clipboard
 xsel -bi < snap-share.txt
 xsel -bo
 rm snap-share.txt
fi
rm -f $f
notify-send "Done. Press Ctrl+V to paste the URL of your shot! and click this notification to see the link. :)"
#xsel -bo|zenity --text-info --width 530
echo `xsel -bo`|xargs -0 notify-send
